language: java
sudo: false
script: sbt clean test
before_install:
  - sudo apt-get update -qq
  # http://thrift.apache.org/docs/install/debian
  - sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  # http://archive.apache.org/dist/thrift/
  - wget http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3
  - ./configure --enable-libs=no --enable-tests=no --enable-tutorial=no --with-cpp=no --with-c_glib=no --with-java=yes --with-ruby=no --with-erlang=no --with-go=no --with-nodejs=no
  - sudo make install
  - cd ..
